- name: Install unzip
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Create alloy group
  ansible.builtin.group:
    name: "{{ service_group }}"
    system: true
  become: true

- name: Create alloy user
  ansible.builtin.user:
    name: "{{ service_user }}"
    groups: "{{ [ service_group ] + alloy_user_groups }}"
    system: true
    create_home: false  # Appropriate for a system user, usually doesn't need a home directory
  become: true

- name: Download alloy binary
  ansible.builtin.get_url:
    url: "{{ binary_url }}"
    dest: "/tmp/alloy-{{ version }}.zip"
    mode: '0755'
  become: true

- name: Extract alloy binary
  ansible.builtin.unarchive:
    src: "/tmp/alloy-{{ version }}.zip"
    dest: "/tmp"
    remote_src: yes
  become: true

- name: Copy installed binary to installation dir
  ansible.builtin.copy:
    src: "/tmp/alloy-linux-{{ arch }}"
    dest: "{{ installation_dir }}/alloy-linux-{{ arch }}"
    remote_src: yes
  become: true
  notify: Restart alloy
