- name: Check if alloy service is active
  ansible.builtin.shell: systemctl is-active alloy
  register: alloy_service_status
  ignore_errors: true
  listen: "Reload alloy"

- name: Restart alloy service if not active
  ansible.builtin.service:
    name: alloy
    state: restarted
  when: alloy_service_status.stdout != "active"
  listen: "Reload alloy"

- name: Reload alloy service if active
  ansible.builtin.service:
    name: alloy
    state: reloaded
  when: alloy_service_status.stdout == "active"
  listen: "Reload alloy"

- name: Check alloy is started properly
  ansible.builtin.include_tasks: ga-started.yml
  listen: "Reload alloy"

- name: Restart alloy
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
  become: true
  listen: "Restart alloy"

- name: Check alloy is started properly
  ansible.builtin.include_tasks: ga-started.yml
  listen: "Restart alloy"
